### ISSUE TITLE
Error on first execution of npm-start

### ISSUE THREAD

**Issue by abjrcode** [react-community/create-react-native-app#101]
Following the [sample code](https://facebook.github.io/react-native/blog/2017/03/13/introducing-create-react-native-app.html) listed on the launch event of Create React Native App.

Doing `npm-start` and immediately getting `'yarn' is not recognized as an internal or external command,
operable program or batch file.`

I know how to fix this of-course, but the question is it expected and is `yarn` a known dependency because I can't see it mentioned in the installation script ?

At the same time, the process continues but can't open the app with the QR code. It is just stuck :(

**Comment by dikaiosune** [comment]
Can you paste the full error output please?

**Comment by abjrcode** [comment]
That is is the full error output. I then see the QR and that the dev server is running on some port but can't load it in the app on the phone.

I am running on Windows 10 with only Node installed.

**Comment by dikaiosune** [comment]
Interesting. If you update `react-native-scripts` to at least 0.0.23, you can specify the `REACT_NATIVE_PACKAGER_HOSTNAME` to provide a specific IP address. 

To answer your previous question: create-react-native-app defaults to yarn, but it is not a hard dependency. Earlier versions of the init script would print the "can't find yarn" message before continuing with npm, but that should no longer be the case as long as you update create-react-native-app itself.

Giving this a close since it sounds like the underlying issues have been resolved. If you run into more networking problems, please open issues for them!

**Comment by abjrcode** [comment]
Unfortunately updating the package to the latest version didn't help. Actually it made things worse.
I can't run the app at all now, I get a red screen after 5 mins on mobile phone with all kinds of errors.

Plus I still see the `yarn` packager problem.

**Comment by abjrcode** [comment]
I know this is not very helpful for diagnosing the problem, but the thing is I don't know what the problem is.
I have installed the latest version of `create-react-native-app` again. I still get the message about `yarn` again.
Trying to open the application with the mobile phone times out, it just doesn't work.
If there any info or logs I can provide to help diagnose this then please let me know and I will be happy to provide.

**Comment by dikaiosune** [comment]
The message about yarn is an issue with upstream React Native, and will be resolved soon hopefully.

The timeouts sound like a networking issue, have you tried the steps in the user guide for troubleshooting that?

**Comment by abjrcode** [comment]
All right. I didn't know about that section :(
Thanks a lot for the help 👍 
I will check it.

**Comment by abjrcode** [comment]
The mobile phone and the laptop are indeed on the same network.
Can't access the both HTTP URLs from the mobile phone though, although they are accessible from the browser on the machine itself.
Adding firewall rules for those two ports is not helping :)

Will try a few more things but I am running of out of ideas :(

Kind regards,

**Comment by dikaiosune** [comment]
Hm, that sounds like you have a somewhat strange networking situation. Unfortunately I don't have time to troubleshoot individual networking setups. One thing you might try is installing [XDE](https://docs.expo.io/versions/v15.0.0/introduction/installation.html) which uses network tunnels to attempt to solve this problem.

**Comment by abjrcode** [comment]
Finally I found the solution to my problem. I didn't even need to open the required ports on the Windows firewall.
The problem was probably that network discovery was turned off.
My solution was switching my network profile to private and then turning on network discovery and file & printer sharing on.

Thank you for the help and walking with me through debugging this problem.
