### ISSUE TITLE
Cannot find module './build/Release/DTraceProviderBindings'

### ISSUE THREAD

**Issue by tusharkhatiwada** [react-community/create-react-native-app#135]
## Description

Hi, I'm getting the following issue (screenshot attached too) after updating the CRNA app. I changed the version from the package.json and sdk version from app.json file. Whenever I run `yarn start`, it displays some error but the app works fine though.

## Observed Behavior

```
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/xxxx/xx/xx/xx/xx/xx/xx/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
```

## Environment

* `npm ls react-native-scripts`: react-native-scripts@0.0.25
* `npm ls react-native`: react-native@0.42.3
* `npm ls expo`: expo@15.1.2
* `node -v`: v7.4.0
* `npm -v`: 4.0.5
* `yarn --version`: 0.21.3
* `watchman version`: 4.7.0

Also specify:

1. Operating system: MacOS 10.12.4
2. Phone/emulator/simulator & version: NA

<img width="1302" alt="screen shot 2017-03-29 at 11 07 50 am" src="https://cloud.githubusercontent.com/assets/5126590/24440071/b8aa5452-1471-11e7-9aca-7e8fe2b880cc.png">

**Comment by dikaiosune** [comment]
Hi! Thanks for the report! Can you paste the output of `yarn list xdl`?

**Comment by tusharkhatiwada** [comment]
@dikaiosune : Here's the output:
**`xdl@37.0.1`**

**Comment by dikaiosune** [comment]
I'm not sure why xdl is showing these issues, as the release process is supposed to clean up any dtrace stuff (although I didn't work on that, maybe @jesseruder remembers more details?). From a quick google it seems like an issue like a not-yet-accepted Xcode license agreement could cause problems?

c.f. https://github.com/trentm/node-bunyan/issues/216#issuecomment-288214835

If this crops up for more users, might be worth looking at a logger which doesn't attempt to use any native modules.

**Comment by wass3r** [comment]
Same issue here. In my case the stated error shows up three times sequentially.

* `npm ls react-native-scripts`: react-native-scripts@0.0.27
* `npm ls react-native`: react-native@0.42.3
* `npm ls expo`: expo@15.1.3
* `node -v`: v7.7.0
* `npm -v`: 4.1.2
* `yarn --version`: 0.23.2
* `watchman --version`: 4.7.0
* `yarn list xdl`: xdl@37.0.2

1. Operating system: MacOS 10.12.4
2. Phone/emulator/simulator & version: NA

**Comment by dikaiosune** [comment]
@wass3r do you have xcode installed? and if so, have you accepted the license agreement?

**Comment by wass3r** [comment]
@dikaiosune I have .. by using `sudo xcodebuild -license accept`, but to be sure I also used the interactive mode with `sudo xcodebuild -license`. Same result.

**Comment by babenzele** [comment]
I accepted the license but am still receiving this error.

**Comment by janhoogeveen** [comment]
Same issue here. 

```yarn list xdl``` results in:

```
yarn list v0.24.4
└─ xdl@40.0.0
✨  Done in 1.20s.
```

**Comment by samfeder** [comment]
Same here, exact same version and problem as @janhoogeveen.

**Comment by encorex** [comment]
Same here, with:

yarn list v0.24.5
└─ xdl@37.0.2
✨  Done in 1.34s.

**Comment by edward-s** [comment]
I have the same issue
main reason why I stopped using CRNA altogether, and used expo XDE as a workaround for now

**Comment by jzabala** [comment]
Same here with:

yarn list v0.24.5
└─ xdl@37.0.2
✨  Done in 1.37s.

**Comment by dikaiosune** [comment]
I think we probably need to stop transitively depending on bunyan based on:

https://github.com/trentm/node-bunyan/issues/216
https://github.com/trentm/node-bunyan/issues/60
https://github.com/trentm/node-bunyan/issues/66

cc @jesseruder @brentvatne I think we need to replace bunyan in xdl for this to be fixed.

**Comment by jmlavoier** [comment]
Same issue here:

`yarn list xdl` is:

yarn list v0.24.5
✨  Done in 1.26s.

**Comment by jmlavoier** [comment]
I figured out this issue: 
https://stackoverflow.com/questions/37550100/cannot-find-module-dtrace-provider

**Comment by ssteinerx** [comment]
I followed the instructions in the Stack Overflow referenced above and it did not solve the issue for me.

* React Native version: 
```
yarn ls v0.17.10
└─ react-native@0.44.3
```
* Platform: IOS
* Development Operating System: OS X, 10.11.6
* Build tools: didn't explicitly use any, Xcode 8.2.1, 8C1002 is on system

**Comment by developerworks** [comment]
```
➜  create_rn_app git:(master) yarn list xdl
yarn list v0.24.6
└─ xdl@41.1.0
✨  Done in 0.79s.
```

Same error

**Comment by brentvatne** [comment]
this comment seems useful: https://github.com/sysgears/apollo-universal-starter-kit/issues/217#issuecomment-307979616

**Comment by htxiong** [comment]
same issue at here

yarn list v0.24.6
└─ xdl@41.1.0
✨  Done in 0.74s.

**Comment by noevil** [comment]
I change the node version to v6.10.0, everything work.

**Comment by jeantimex** [comment]
I had the same issue, so I followed @babenzele 's suggestion, removed the `node_modules` folder, and ran `yarn install`, the error was gone! Thanks @babenzele!

**Comment by rc452860** [comment]
![image](https://user-images.githubusercontent.com/3949222/27521989-0651d49a-5a55-11e7-8271-65b9f5af64c2.png)

**Comment by jaekschmitt** [comment]
Check your python version. `dtrace-provider` fails to install with any python version >= 3.0.0. 

After 
* switching my python version to 2.7.13 
* nuking my `node_modules` folder
* running `npm i`

I was able to run `npm start` successfully.

**Comment by xuv** [comment]
Just to add my 2¢, indeed, removing `node_modules` and using `npm i` instead of `yarn` solved it.

**Comment by prochafilho** [comment]
@xuv that worked for me! Thank you.

**Comment by ashrewdmint** [comment]
I encountered this and was able to fix it by using a Python version < `3.0.0`, nuking `node_modules` and running `yarn`.

To see what the issue is for your system (or if the above did not solve the problem), run `V=1 node node_modules/dtrace-provider/scripts/install.js`.

The reason for the failure is that the `dtrace-provider` directory does not contain a `build/Release/DTraceProviderBindings.node` file. It doesn't contain this file because the `scripts/install.js` script failed to run.

**Comment by brentvatne** [comment]
in our next release we will remove all dependencies on dtrace-provider, which should make all of these issues go away. sorry about this!

**Comment by bluepeter** [comment]
Looking forward to this! Been driving me crazy. :) Any planned date for the release @brentvatne ?

**Comment by jacksctsai** [comment]
I had the same error. It got fixed after I switched to python2 (I'm using anaconda) and then nuking `node_module` and re-run `npm install`.

**Comment by brentvatne** [comment]
This is fixed now. We no longer depend on dtrace! :)

**Comment by karlgroves** [comment]
I know this is an old issue but I wanted to comment on it in case anyone else has the same issue I had.

My issue was caused by having parentheses in my path. 
`/users/karlgroves/Dropbox (Personal)/foo/bar/bat/project...`

Moving the project to a path without the parens worked for me.
You'll need to wipe out `node_modules` and reinstall again.
