### ISSUE TITLE
Run iOS script fails because of Simulator code 60

### ISSUE THREAD

**Issue by JackWReid** [react-community/create-react-native-app#62]
After installing all the dependencies, I run `npm run ios` and it fails at the simulator step with the following terminal output:

```
Starting packager...
Starting simulator...
Failed to start simulator:

Error: Process exited with non-zero code: 60

Exiting...
```

However, the Simulator does start up and Exponent starts up but fails to connect to the server.

I'm having trouble isolating the problem because I haven't changed anything from the initial project files.

**Comment by dikaiosune** [comment]
Hi! Thanks for the report. This is an issue we've seen a few times, and it's usually resolved by a reboot or by clearing the simulator device's content and settings. Can you let me know if either of those things resolve the issue?

**Comment by JackWReid** [comment]
Yep, solved by hitting `Reset Content and Settings` in the Simulator. Similar to #67 in this regard. Thanks for the troubleshoot!

**Comment by jonathandavidpollock** [comment]
Reset Content and Settings seems to fix the issue. However, on my machine, I have to do this whenever the Simulator App restarts. I thought something was wrong with my machine. I factory reset everything and started from scratch. I'm still getting the same error, but the Reset Content and Settings works.

**Comment by adiakritos** [comment]
It appears this error has resurfaced in Monterey for me. 

Here is the error I get:

```Error: xcrun exited with non-zero code: 60
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=60):
Unable to boot the Simulator.
launchd failed to respond.
Underlying error (domain=com.apple.SimLaunchHostService.RequestError, code=4):
	Failed to start launchd_sim: could not bind to session, launchd_sim may have crashed or quit responding
```

**Comment by Onyelaudochukwuka** [comment]
having same issue how was yours resolved @adiakritos

**Comment by sujitmemane** [comment]
> adiakritos
is your issue resolved ?

**Comment by ceconcarlsen** [comment]
Reset Content and Settings solved the issue. For Mac users, at the TopBar, under Device > `Erase All Content  and Settings ...`

**Comment by hems** [comment]
i'm on OSX 12.7 Monterey, in my case i had to go to System -> Storage -> Developer and nuke XCode cache as described here:

https://forums.developer.apple.com/forums/thread/718750

now it works!

**Comment by AAwaisYaseen** [comment]
If you are not able to boot the simulator and the option for `Reset Content and Settings` is greyed out, You can try this

Mac --- > System Settings --- > Storage --- > Developer --- > Delete `Xcode Caches`.

Restart the simulator, it will work fine.

**Comment by NishantGautam023** [comment]
I had the same issue for macOS Sonoma (14.2.1), **Deleting the Xcode caches** worked thanks :)  @AAwaisYaseen

**Comment by webdiego** [comment]
> Mac --- > System Settings --- > Storage --- > Developer --- > Delete `Xcode Caches`

This is the answer! Thanksss

**Comment by DaltonHarvey** [comment]
Thanks @AAwaisYaseen 


Deleting the `Xcode Caches` solved the issue

**Comment by odusseys** [comment]
I know this is old but are there plans to ever fix this? Quite annoying to have to clear the cache all the time, especially if developing stuff where having a persistent file storage is helpful.

**Comment by upnorth** [comment]
> If you are not able to boot the simulator and the option for `Reset Content and Settings` is greyed out, You can try this
> 
> Mac --- > System Settings --- > Storage --- > Developer --- > Delete `Xcode Caches`.
> 
> Restart the simulator, it will work fine.

Confirmed to work on Sonoma as well, although I couldn't find "Reset Content and Settings" in the sim but did find the Xcode caches to delete. Just starting out learning React Native with Expo, this was a big help through an otherwise very basic tutorial, thanks!

**Comment by kavinraju** [comment]
> > If you are not able to boot the simulator and the option for `Reset Content and Settings` is greyed out, You can try this
> > Mac --- > System Settings --- > Storage --- > Developer --- > Delete `Xcode Caches`.
> > Restart the simulator, it will work fine.
> 
> Confirmed to work on Sonoma as well, although I couldn't find "Reset Content and Settings" in the sim but did find the Xcode caches to delete. Just starting out learning React Native with Expo, this was a big help through an otherwise very basic tutorial, thanks!

This helped to solve this issue!

**Comment by shal0mdave** [comment]
> If you are not able to boot the simulator and the option for `Reset Content and Settings` is greyed out, You can try this
> 
> Mac --- > System Settings --- > Storage --- > Developer --- > Delete `Xcode Caches`.
> 
> Restart the simulator, it will work fine.

This worked for me, thanks.

**Comment by anhtuank7c** [comment]
> If you are not able to boot the simulator and the option for `Reset Content and Settings` is greyed out, You can try this
> 
> Mac --- > System Settings --- > Storage --- > Developer --- > Delete `Xcode Caches`.
> 
> Restart the simulator, it will work fine.

Thank you so much ❤️

**Comment by madelineleclair** [comment]
> i'm on OSX 12.7 Monterey, in my case i had to go to System -> Storage -> Developer and nuke XCode cache as described here:
https://forums.developer.apple.com/forums/thread/718750
now it works!

Had similar problem. This worked for me.
